# Site settings
title: Welcome to Sally's Homepage!
email: ssyjun2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Data Mining Researcher with a demonstrated history of IT Project management. Skilled in Natural Language Processing, Knowledge Base, Machine Learning, Deep Learning and Software Engineering

baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


